### ISSUE TITLE
Exceeded 30 redirects

### ISSUE THREAD

**Issue by akamhy** [akamhy/waybackpy#91]
```
akamhy at device in ~
$ waybackpy -u https://github.com/akamhy/videohash/blob/main/videohash/vhash.py -s
Traceback (most recent call last):
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/waybackpy/utils.py", line 377, in _get_response
    return s.get(url, headers=headers)
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/waybackpy/cli.py", line 15, in _save
    return obj.save()
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/waybackpy/wrapper.py", line 160, in save
    instance=self,
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/waybackpy/utils.py", line 242, in _archive_url_parser
    res = _get_response(url, headers=headers)
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/waybackpy/utils.py", line 389, in _get_response
    raise exc
waybackpy.exceptions.WaybackError: Error while retrieving https://web.archive.org/web/202101290913/https://github.com/akamhy/videohash/blob/main/videohash/vhash.py.
Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akamhy/.pyenv/versions/3.5.3/bin/waybackpy", line 33, in <module>
    sys.exit(load_entry_point('waybackpy==2.4.1', 'console_scripts', 'waybackpy')())
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/waybackpy/cli.py", line 327, in main
    print(args_handler(parse_args(argv)))
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/waybackpy/cli.py", line 178, in args_handler
    output = _save(obj)
  File "/home/akamhy/.pyenv/versions/3.5.3/lib/python3.5/site-packages/waybackpy/cli.py", line 31, in _save
    raise WaybackError(err)
waybackpy.exceptions.WaybackError: Error while retrieving https://web.archive.org/web/202101290913/https://github.com/akamhy/videohash/blob/main/videohash/vhash.py.
Exceeded 30 redirects.

akamhy at device in ~
$ 

```

**Comment by akamhy** [comment]
Why are we even retrieving <https://web.archive.org/web/202101290913/https://github.com/akamhy/videohash/blob/main/videohash/vhash.py> for a save request? Maybe they (IA) started redirecting to the archive, will have to check it.

**Comment by akamhy** [comment]
Not an issue anymore after the recent 2022 JAN commits
